### ISSUE TITLE
source dir and exe name are the same

### ISSUE THREAD

**Issue by TheAwesome98-Real** [johnpayne-dev/MinecraftC#14]
the source folder and the executable name are the same, meaning

- if you try building it fails because it can't create a file over a directory
- if you make clean it wipes the source folder

**Comment by johnpayne-dev** [comment]
Are you doing an in source build? I don't think this should happen if you create a "Build" directory and build from there, in-source builds are generally advised against

**Comment by TheAwesome98-Real** [comment]
oh i didn't even realise there were instructions, because the last time i checked the readme was when it still used a sh file to build

**Comment by TheAwesome98-Real** [comment]
same problem if i make a Build folder

**Comment by johnpayne-dev** [comment]
Make sure you delete the CMakeCache from before

**Comment by TheAwesome98-Real** [comment]
ah

**Comment by TheAwesome98-Real** [comment]
yeah i am new to cmake so that makes sense
