### ISSUE TITLE
text-shadow is greenish

### ISSUE THREAD

**Issue by TheAwesome98-Real** [johnpayne-dev/MinecraftC#16]
![image](https://user-images.githubusercontent.com/59254971/183690420-31551178-86d0-44be-9a3e-47ea36a6788f.png)
![image](https://user-images.githubusercontent.com/59254971/183690569-57ca8e49-90c2-416c-8703-adb6cff1fff8.png)

**Comment by johnpayne-dev** [comment]
should be fixed in latest dev branch now
