### ISSUE TITLE
Flowing water crashes the game on MacOS

### ISSUE THREAD

**Issue by SuperStik** [johnpayne-dev/MinecraftC#8]
Attempting to update a water block (whether with TNT or just by punching a block next to it) causes the game to crash, and gives a "segmentation fault" error.

**Comment by mudkipdev** [comment]
Cannot replicate.

**Comment by johnpayne-dev** [comment]
It was an issue that occurred on some platforms when compiling with optimizations enabled, I assumed it was a compiler bug but I couldn't figure much out past that. Regardless, I'm currently doing a full refactor of the project that should get rid of the issue.

**Comment by johnpayne-dev** [comment]
Should be fixed now, reopen if it happens again
