### ISSUE TITLE
Survival Test and 32 Bit windows support

### ISSUE THREAD

**Issue by Magallanesmapping321** [johnpayne-dev/MinecraftC#9]
Just wondering if there would be a 0.30 survival mode for minecraftc and a 32 bit windows version for my old computer

**Comment by mudkipdev** [comment]
The README says survival test will not be supported. I think you can compile the 32-bit version yourself.

**Comment by johnpayne-dev** [comment]
32-bit version has just been added, and as mudkipdev stated, survival is not planned
